#!/usr/bin/env bash
set -euo pipefail

sudo -v # ask for password, cache credentials

# Wait until kissat exists
while ! pgrep -x kissat >/dev/null; do
    sleep 0.01
done

BEST_CORE="8,11"
PID="$(pgrep -x kissat)"

echo 0 > sudo /proc/sys/kernel/randomize_va_space
sudo cpupower frequency-set -g performance
sudo renice -n -20 -p "$PID"
sudo taskset -cp "$BEST_CORE" "$PID"
sudo chrt -f -p 99 "$PID"
sudo ionice -c2 -n0 -p "$PID"
sudo prlimit --pid "$PID" --memlock=unlimited

# Start the logging
python watch_plot.py
